### ISSUE TITLE
Questions and an Offer of Help, If Wanted.

### ISSUE THREAD

**Issue by ryaminal** [gkkachi/firestore-grpc#1]
This crate seems super useful. I have some questions.

How did you get the proto files? Is there a way we can help to automate pulling the latest protos and having it build nightly or something?

Tonic seems like it does most of the heavy lifting here. We are looking to use some Firebase stuff(so, not just Firestore) and this gRPC crate looks like it would be great for us to use and help contribute to.

**Comment by gkkachi** [comment]
Thanks for your interest!

You can get the proto files from [this repository](https://github.com/googleapis/googleapis). See `update.sh` for details. This script downloads the latest protos and moves them into the right place.
Run `rustup run nightly cargo build` if you want to build it nightly.

If you have some ideas to improve this crate, please tell me how to. A contribution is welcome!
