### ISSUE TITLE
Given example is out of date and doesn't work - better to remove it

### ISSUE THREAD

**Issue by chokosabe** [gkkachi/firestore-grpc#6]
The example given is out of date (making calls that no longer exist in most current version of code). I also think it never worked? Better to remove it. Spent a couple of hours debugging it

**Comment by gkkachi** [comment]
@chokosabe 
I updated the example. https://github.com/gkkachi/firestore-grpc/commit/ded3834743b6a67e60026ca300d3565a608b17bd
Does it work?

**Comment by chokosabe** [comment]
Hi @gkkachi, just tried it and it works. I tried it with the version numbers you included  in the example.

**Comment by gkkachi** [comment]
Thank you for trying!
